from battlefield.bots.bot import Bot
from battlefield.bots.random_bot import *
from battlefield.bots.simple_bot import *
from battlefield.bots.observe_bot import *
from battlefield.bots.ismcts_bot import *
from battlefield.bots.human_bot import *
from battlefield.bots.nn_bot import *
from battlefield.bots.stats_bot import *
from battlefield.bots.single_mcts_bot import *
from battlefield.bots.cfr_bot import *
from battlefield.bots.learning_bot import *
from battlefield.bots.observe_beater_bot import *
from battlefield.bots.deeprole import *
